name: skibidi
description: "SKIBIDI TOILET"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - diamehdog.mp3
